# ============================================================
# invertoTimer Configuration
# https://github.com/Our-Island/invertoTimer/wiki/Global-Settings
#
# You can also read the quick start article!
# ============================================================
lang: "en_us"

timezone: "Etc/UTC"

limitation:
  mode: blacklist
  list:
    - game1
    - test1
